apiVersion: apps/v1
# ở đây phiên bản cũ hơn của kubernetes có dạng extensions/v1beta1
kind: Deployment
# kind là loại Deployment
metadata:
  name: spring-deployment
  namespace: ingress-nginx
spec:
  replicas: 3
  # replica ở đây sẽ tạo ra 2 pods luôn luôn chạy, khi một số pods bị down hay chết hay bất kì lý do nào đó sẽ tự động tạo lại số lượng pods bằng 2
  selector:
    matchLabels:
      app: spring-deployment
  template:
    metadata:
      labels:
        app: spring-deployment
    spec:
      containers:
      - name: spring-deployment
      # image của container docker
        image: eureka:dev-5c999968
        ports:
        # port bên trong container
        - containerPort: 8080
---
apiVersion: v1
# kind là loại Service
kind: Service
metadata:
  name: spring-svc
  namespace: ingress-nginx
spec:
  selector:
    app: spring-deployment
  type: ClusterIP
  ports:
    - name: spring-deployment
      protocol: TCP
      port: 8080
      targetPort: 8080