apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: ingress-nginx
spec:
  project: default
  source:
    repoURL: https://github.com/vannguyen14893/argo-cd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
